apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: decidim-an-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    cert-manager.io/issuer: letsencrypt-prod
spec:
  rules:
  - host: petitions-an.osp.cat
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: decidim-an-svc
            port:
              number: 80
  tls:
  - hosts:
    - petitions-an.osp.cat
    secretName: decidim-an-ingress-secret-2
